apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::802995400930:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10WLE46LP3H59
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::802995400930:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-19T22:02:26Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-19T22:02:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1375"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0e736593-476d-4fb7-9bf5-250ee44e30f6
